[package]
name = "openplay_piggy_bank"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
version = "0.0.1"

[dependencies]
openplay_core = { local = "../openplay_core" }


[addresses]
openplay_piggy_bank = "0x0"
