[package]
name = "openplay_core"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
version = "0.0.1"

[dependencies]
Sui = { local = "../../../sui_from_source/crates/sui-framework/packages/sui-framework" }

[addresses]
openplay_core = "0x1"
